version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "07:30"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 2
