frontend:
  - changed-files:
      - any-glob-to-any-file: "src/**"
backend:
  - changed-files:
      - any-glob-to-any-file: "server/**"
database:
  - changed-files:
      - any-glob-to-any-file: "supabase/**"
ci-cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "**/*.md"
