name: Bug report
description: Report a reproducible defect affecting behavior or reliability
title: "bug: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Concise description of the bug and impact.
      placeholder: What is broken and who is affected?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Deterministic steps to reproduce.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - sev1 - production down or security issue
        - sev2 - major feature broken
        - sev3 - minor defect/workaround exists
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: branch, commit, browser, OS
