name: Feature request
description: Propose a new capability or meaningful improvement
title: "feat: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user or business problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Preferred solution and rough implementation shape.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - p0 - critical
        - p1 - high
        - p2 - medium
        - p3 - low
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of testable outcomes.
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
