// This file is automatically generated. Do not edit it directly.
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

declare global {
  interface Window {
    __supabaseClient?: SupabaseClient<Database>;
  }
}

// * Read from environment variables (prioritize env vars over hardcoded values)
// * Supports both VITE_ prefix (Vite) and direct SUPABASE_ prefix (Node/Vercel)
const getEnvVar = (key: string): string | undefined => {
  // Try Vite env first (browser)
  if (typeof import.meta !== "undefined" && import.meta.env) {
    const viteKey = `VITE_${key}`;
    if (import.meta.env[viteKey]) return import.meta.env[viteKey];
    if (import.meta.env[key]) return import.meta.env[key];
  }
  // Try Node process env
  if (typeof process !== "undefined" && process.env) {
    if (process.env[key]) return process.env[key];
    if (process.env[`VITE_${key}`]) return process.env[`VITE_${key}`];
  }
  return undefined;
};

const SUPABASE_URL =
  getEnvVar("SUPABASE_URL") || "https://ocghxwwwuubgmwsxgyoy.supabase.co"; // Fallback for development

const SUPABASE_ANON_KEY =
  getEnvVar("SUPABASE_ANON_KEY") ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jZ2h4d3d3dXViZ213c3hneW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTgzMjksImV4cCI6MjA2NTY3NDMyOX0.93cpwT3YCC5GTwhlw4YAzSBgtxbp6fGkjcfqzdKX4E0"; // Fallback for development

let supabase: SupabaseClient<Database> | null =
  typeof window !== "undefined" ? (window.__supabaseClient ?? null) : null;

let initializationPromise: Promise<SupabaseClient<Database> | null> | null =
  null;

const createSupabaseClient =
  async (): Promise<SupabaseClient<Database> | null> => {
    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      if (process.env.NODE_ENV === "development") {
        console.error(
          "❌ Database Configuration Error: Missing Supabase credentials.",
          "\n   Please check that SUPABASE_URL and SUPABASE_ANON_KEY are set in your .env file.",
          "\n   Expected format:",
          "\n   SUPABASE_URL=https://your-project.supabase.co",
          "\n   SUPABASE_ANON_KEY=your-anon-key"
        );
      }
      return null;
    }

    try {
      if (process.env.NODE_ENV === "development") {
        console.log("🔌 Initializing Supabase connection...");
      }

      const { createClient } = await import("@supabase/supabase-js");

      const authOptions = {
        persistSession: true,
        autoRefreshToken: true,
        storage: (() => {
          try {
            return typeof window !== "undefined"
              ? window.localStorage
              : undefined;
          } catch (error) {
            if (process.env.NODE_ENV === "development") {
              console.warn(
                "⚠️ Local storage unavailable, session persistence disabled:",
                error
              );
            }
            return undefined;
          }
        })(),
      } as const;

      // Get current user name from localStorage to include in headers
      let currentUserName: string | null = null;
      try {
        if (typeof window !== "undefined" && window.localStorage) {
          currentUserName = window.localStorage.getItem("catNamesUser");
        }
      } catch (error) {
        if (process.env.NODE_ENV === "development") {
          console.warn("Could not read user from localStorage:", error);
        }
      }

      const client = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
        auth: authOptions,
        global: {
          headers: {
            "X-Client-Info": "cat-name-tournament",
            ...(currentUserName ? { "x-user-name": currentUserName } : {}),
          },
        },
        db: {
          schema: "public",
        },
      });

      // Test connection with a simple query
      try {
        const { error: testError } = await client
          .from("cat_name_options")
          .select("id")
          .limit(1);

        if (testError) {
          if (process.env.NODE_ENV === "development") {
            console.error(
              "⚠️ Database connection test failed:",
              testError.message
            );
          }
          // Don't fail initialization, just warn
        } else {
          if (process.env.NODE_ENV === "development") {
            console.log("✅ Supabase connection established successfully");
          }
        }
      } catch (testErr) {
        if (process.env.NODE_ENV === "development") {
          console.warn("⚠️ Could not verify database connection:", testErr);
        }
        // Continue anyway - connection might work for actual queries
      }

      if (typeof window !== "undefined") {
        window.__supabaseClient = client;
      }

      return client;
    } catch (error) {
      console.error("❌ Failed to create Supabase client:", error);
      if (process.env.NODE_ENV === "development") {
        console.error(
          "   This could be due to:",
          "\n   - Invalid credentials",
          "\n   - Network connectivity issues",
          "\n   - CORS configuration problems",
          "\n   - Supabase service outage"
        );
      }
      return null;
    }
  };

const getSupabaseClient = async (
  retryCount = 0
): Promise<SupabaseClient<Database> | null> => {
  const MAX_RETRIES = 3;
  const RETRY_DELAY = 1000;

  if (supabase) {
    return supabase;
  }

  if (!initializationPromise) {
    initializationPromise = createSupabaseClient()
      .then((client) => {
        supabase = client;
        return client;
      })
      .catch(async (error) => {
        console.error(
          `❌ Supabase initialization failed (attempt ${retryCount + 1}/${MAX_RETRIES + 1}):`,
          error
        );
        initializationPromise = null;

        // Retry logic for network/temporary errors
        if (retryCount < MAX_RETRIES) {
          const shouldRetry =
            error.message?.includes("fetch") ||
            error.message?.includes("network") ||
            error.message?.includes("timeout");

          if (shouldRetry) {
            const delay = RETRY_DELAY * Math.pow(2, retryCount);
            if (process.env.NODE_ENV === "development") {
              console.log(`⏳ Retrying connection in ${delay}ms...`);
            }
            await new Promise((resolve) => setTimeout(resolve, delay));
            return getSupabaseClient(retryCount + 1);
          }
        }

        return null;
      });
  }

  return initializationPromise;
};

export const getSupabaseClientSync = (): SupabaseClient<Database> | null =>
  supabase;

export const resolveSupabaseClient =
  async (): Promise<SupabaseClient<Database> | null> =>
    getSupabaseClientSync() ?? (await getSupabaseClient());

/**
 * Update the x-user-name header for the current Supabase client
 * Call this when user logs in or out to ensure RLS policies work correctly
 */
export const updateSupabaseUserContext = (userName: string | null): void => {
  if (!supabase) {
    if (process.env.NODE_ENV === "development") {
      console.warn(
        "Cannot update user context: Supabase client not initialized"
      );
    }
    return;
  }

  // Update the headers for future requests
  // Note: This uses the internal API of the Supabase client
  // @ts-ignore - accessing internal property
  if (supabase.rest && supabase.rest.headers) {
    if (userName) {
      // @ts-ignore
      supabase.rest.headers["x-user-name"] = userName;
    } else {
      // @ts-ignore
      delete supabase.rest.headers["x-user-name"];
    }
  }

  if (process.env.NODE_ENV === "development") {
    console.log(`🔄 Updated Supabase user context: ${userName || "(none)"}`);
  }
};

if (!supabase) {
  void getSupabaseClient();
}
